void loadusers();
int main(int argc,char *argv[]);
void error(char *msg);
void print_users_list();
void print_active_users_list();
void adduser(char username[20],char password[20]);
void keyboard(char *cmd);
void SIGhandler(int sig);
void shutdown();
struct usersActive *add_to_active_users_list(int pid,char username[20]);
int validate(char username[20],char password[20]);
int check_if_user_is_logged(char username[20]);
void *receiver(void *arg);
extern struct usersActive *active_curr;
extern struct usersActive *active_head;
extern struct users *curr;
extern struct users *head;
